homepage:
  path:      /
  defaults:  { _controller: AppBundle:StorefrontProduct:homepage }

#
# Storefront
#
storefront:
  prefix: /storefront
  resource: "@AppBundle/Resources/config/routing/storefront.yml"

#
# Admin
#
admin:
  prefix: /admin
  resource: "@AppBundle/Resources/config/routing/admin.yml"

#
# Cart
#
cart:
  prefix: /cart
  resource: "@AppBundle/Resources/config/routing/cart.yml"

#
# 3rd-party
#
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"