admin_index:
  path:      /
  defaults:  { _controller: AppBundle:Admin:index }

admin_product_new:
  path:      /product/new
  methods:   [GET, POST]
  defaults:  { _controller: AppBundle:AdminProduct:new }

admin_product_update:
  path:      /product/update/{id}
  defaults:  { _controller: AppBundle:AdminProduct:update }

admin_product_delete:
  path:      /product/delete/{id}
  defaults:  { _controller: AppBundle:AdminProduct:delete }

admin_product_list:
  path:      /product/list
  defaults:  { _controller: AppBundle:AdminProduct:list }

admin_category_new:
  path:      /category/new
  defaults:  { _controller: AppBundle:AdminCategory:new }

admin_category_update:
  path:      /category/update
  defaults:  { _controller: AppBundle:AdminCategory:update }

admin_category_delete:
  path:      /category/delete/{id}
  defaults:  { _controller: AppBundle:AdminCategory:delete }

admin_category_list:
  path:      /category/list
  defaults:  { _controller: AppBundle:AdminCategory:list }

admin_slide_new:
  path:      /slide/new
  defaults:  { _controller: AppBundle:AdminSlide:new }

admin_slide_update:
  path:      /slide/update
  defaults:  { _controller: AppBundle:AdminSlide:update }

admin_slide_delete:
  path:      /slide/delete/{id}
  defaults:  { _controller: AppBundle:AdminSlide:delete }

admin_slide_list:
  path:      /slide/list
  defaults:  { _controller: AppBundle:AdminSlide:list }

admin_news_new:
  path:      /news/new
  defaults:  { _controller: AppBundle:AdminNews:new }

admin_news_update:
  path:      /news/update
  defaults:  { _controller: AppBundle:AdminNews:update }

admin_news_delete:
  path:      /news/delete/{id}
  defaults:  { _controller: AppBundle:AdminNews:delete }

admin_news_list:
  path:      /news/list
  defaults:  { _controller: AppBundle:AdminNews:list }
